import React from 'react';

import Head from 'next/head';

export const HeadComponent = () => {
  return (
    <Head>
      <title>Street Fabric</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
